### ISSUE TITLE
Rename fields in django admin panel

### ISSUE THREAD

**Issue by AdityaKhatri** [idmc-labs/gidd-server#16]
Update labels in django admin panel based on the screenshot below.
>NOTE: If any of these changes are not recommended, please outline them here.

![Image](https://user-images.githubusercontent.com/7893887/204232685-42c02538-e056-4f0a-952b-ceaaf54081c9.png)

**Comment by kopitek8** [comment]
1. Rename “Static pages” to “HOMEPAGE - Introduction and Contact information”
2. Done
3. Done
4. Rename title “GIDD Administration” to “IDMC Country Profile and Global Repository Admin”
5. Rename things inside "Global repository of Good Practices":
    - “Good practices” to “PAGES - Good practices pages”
    - “Drivers of displacements” to “Filters - Drivers of displacements”
    - “Focus areas” to “Filters - Focus areas”
    - “Frequently asked questions” to “HOMEPAGE - Frequently asked questions”

**Comment by kopitek8** [comment]
@Rup-Narayan-Rajbanshi Please check this

**Comment by Rup-Narayan-Rajbanshi** [comment]
Sure..
