### ISSUE TITLE
Submit a Good Practice - Remove max character limit in the submission form

### ISSUE THREAD

**Issue by kopitek8** [idmc-labs/gidd-server#37]
## Client Requirement

Remove the character limit for the body of text, or double the current limit if it has to remain.

## Where Are They?

- Admin panel
- Submit a Good Practice modal (frontend)

## To Do

- Remove the max character limit of 10,000 in both English and French textfields

**Comment by bramverweij** [comment]
Tested in Staging, the Character limit has been removed for the following:

    Description of the project [en]:
    Description of the project [fr]:
    Media and resource links (Links to any relevant reports, evaluations or other documents) [en]:
    Media and resource links (Links to any relevant reports, evaluations or other documents) [fr]:
